# Generated by Django 3.1.4 on 2021-01-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='song_id',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
