# Generated by Django 3.1.4 on 2021-01-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='song_id',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
